In [ ]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [6]:
train_labels = []
train_samples = []

In [9]:
for i in range(50):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    random_elder = randint(65,100)
    train_samples.append(random_elder)
    train_labels.append(0)
    
for i in range(1000):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    random_elder = randint(65,100)
    train_samples.append(random_elder)
    train_labels.append(1)

In [11]:
for i in train_samples:
    print (i)

44
50
94
16
86
27
93
63
75
61
84
52
88
31
70
64
94
45
94
52
92
49
96
58
66
64
89
53
95
15
91
15
69
55
79
45
67
27
83
40
74
39
71
53
79
13
82
56
82
47
68
52
66
39
92
31
74
13
72
27
84
60
70
30
68
37
97
25
76
15
76
41
76
23
81
15
67
39
83
15
99
40
88
52
88
53
99
39
95
20
89
54
75
56
93
62
84
29
65
35
79
38
92
38
80
55
72
43
88
53
73
34
65
15
73
14
90
51
85
60
88
56
78
17
79
61
90
32
83
40
82
54
97
34
68
43
75
31
84
47
65
16
82
63
69
54
72
21
85
47
66
18
90
56
98
22
71
14
84
32
93
59
67
15
68
18
88
21
87
28
76
26
76
19
69
53
80
21
86
17
97
62
67
61
71
24
73
20
94
21
75
44
99
16
93
36
80
14
68
13
72
18
74
54
71
41
65
31
65
41
96
16
86
48
65
61
89
64
79
26
76
28
91
64
77
36
94
13
83
24
71
54
76
15
71
46
79
29
77
18
77
58
87
49
88
13
75
23
83
34
87
19
65
39
97
38
73
41
83
17
98
31
66
40
93
14
72
17
91
56
91
28
99
29
82
50
85
38
79
64
66
48
95
63
96
57
93
45
84
52
90
52
81
29
87
13
96
46
78
60
81
24
68
17
84
60
65
21
96
43
94
45
69
54
94
28
91
62
79
30
75
33
88
45
92
42
69
27
91
60
99
16
89
2

In [12]:
for i in train_labels:
    print (i)

1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0


In [21]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
print (train_labels)

[1 1 1 ... 0 1 1]


In [20]:
train_labels, train_samples = shuffle(train_labels, train_samples)
print (train_labels, train_samples)
print (train_labels)

[1 1 1 ... 0 1 1] [ 92  68  15 ...  16  66 100]
[1 1 1 ... 0 1 1]


In [19]:
scaler = MinMaxScaler(feature_range = (0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))
print (scaled_train_samples)

[[0.8045977 ]
 [0.06896552]
 [0.72413793]
 ...
 [0.44827586]
 [0.74712644]
 [0.83908046]]
